### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by dunglee** [coryhouse/pluralsight-redux-starter#10]
Node version: 6.3.0 and 5.12.0

npm version: 3.10.3

Operating system: windows 10

Command line used:

Steps to reproduce: npm install , npm start -s

module.js:442
    throw err;
    ^

Error: Cannot find module './_baseClone'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dung\Desktop\Demo\node_modules\babel-core\node_modules\babel-template\node_modules\lodash\cloneDeep.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by coryhouse** [comment]
Hi @dunglee - Have you tried everything here? https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by dunglee** [comment]
I tried already

**Comment by coryhouse** [comment]
Hrm. It's running fine for me with those versions on Windows 10 using the Windows command line. Can you provide your npm-debug.log?

**Comment by dunglee** [comment]
There's no npm-debug.log after npm start -s

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Dung\Desktop\Demo>npm start -s
module.js:442
    throw err;
    ^

Error: Cannot find module './_baseClone'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dung\Desktop\Demo\node_modules\babel-core\node_modules\babel-template\node_modules\lodash\clone
Deep.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

C:\Users\Dung\Desktop\Demo>

**Comment by coryhouse** [comment]
Can you please share your code so I can try reproducing the issue?

**Comment by dunglee** [comment]
Can you tell me what code I share after following these steps

1. Install Node 6. Need to run multiple versions of Node? Use nvm or nvm-windows
2. Clone this repository. - git clone https://github.com/coryhouse/pluralsight-redux-starter.git or download the zip
3. Make sure you're in the directory you just created. - cd pluralsight-redux-starter
4. Install Node Packages. - npm install
5. Run the app. - npm start -s

**Comment by dunglee** [comment]
Hi @coryhouse 

It's okay.
I updated the lastest npm & node version.

Thank you very much
