### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by oluoyefeso** [coryhouse/pluralsight-redux-starter#106]
# Wait, try this first...
Before opening an issue, [please try these things first](https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first).

If that list doesn't help you fix the problem, fill out the info below.

Node version: 10.15.2

npm version: 6.9.0

Operating system: Windows 10

Command line used:

Steps to reproduce:

command window
*****************
Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Tumise>cd dev

C:\Users\Tumise\dev>cd psr
The system cannot find the path specified.

C:\Users\Tumise\dev>cd prs

C:\Users\Tumise\dev\prs>npm start

> pluralsight-redux-starter@1.0.0 prestart C:\Users\Tumise\dev\prs
> babel-node tools/startMessage.js

Starting app in dev mode...

> pluralsight-redux-starter@1.0.0 start C:\Users\Tumise\dev\prs
> npm-run-all --parallel test:watch open:src lint:watch

> pluralsight-redux-starter@1.0.0 test:watch C:\Users\Tumise\dev\prs
> npm run test -- --watch

> pluralsight-redux-starter@1.0.0 open:src C:\Users\Tumise\dev\prs
> babel-node tools/srcServer.js

> pluralsight-redux-starter@1.0.0 lint:watch C:\Users\Tumise\dev\prs
> npm run lint -- --watch

> pluralsight-redux-starter@1.0.0 test C:\Users\Tumise\dev\prs
> mocha --reporter progress tools/testSetup.js "src/**/*.test.js" "--watch"

> pluralsight-redux-starter@1.0.0 lint C:\Users\Tumise\dev\prs
> esw webpack.config.* src tools "--watch"

C:\Users\Tumise\dev\prs\webpack.config.dev.js:33
  plugins: [new _webpack2.default.HotModuleReplacementPlugin(), new _webpack2.default.NoErrorsPlugin()],
                                                                ^

TypeError: _webpack2.default.NoErrorsPlugin is not a constructor
    at Object.<anonymous> (C:/Users/Tumise/dev/prs/webpack.config.dev.js:24:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (C:\Users\Tumise\dev\prs\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Tumise\dev\prs\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:/Users/Tumise/dev/prs/tools/srcServer.js:4:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pluralsight-redux-starter@1.0.0 open:src: `babel-node tools/srcServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 open:src script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tumise\AppData\Roaming\npm-cache\_logs\2019-04-03T08_33_09_278Z-debug.log

ERROR: open:src: None-Zero Exit(1);
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pluralsight-redux-starter@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tumise\AppData\Roaming\npm-cache\_logs\2019-04-03T08_33_10_060Z-debug.log

C:\Users\Tumise\dev\prs>
********************************
The debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Tumise\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pluralsight-redux-starter@1.0.0~prestart: pluralsight-redux-starter@1.0.0
6 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: PATH: C:\Users\Tumise\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Tumise\dev\prs\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Wolfram Research\WolframScript\;C:\Program Files\nodejs\;C:\Users\Tumise\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Tumise\AppData\Roaming\npm;C:\Users\Tumise\AppData\Local\Programs\Microsoft VS Code\bin
8 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: CWD: C:\Users\Tumise\dev\prs
9 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Args: [ '/d /s /c', 'babel-node tools/startMessage.js' ]
10 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle pluralsight-redux-starter@1.0.0~start: pluralsight-redux-starter@1.0.0
12 verbose lifecycle pluralsight-redux-starter@1.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle pluralsight-redux-starter@1.0.0~start: PATH: C:\Users\Tumise\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Tumise\dev\prs\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Wolfram Research\WolframScript\;C:\Program Files\nodejs\;C:\Users\Tumise\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Tumise\AppData\Roaming\npm;C:\Users\Tumise\AppData\Local\Programs\Microsoft VS Code\bin
14 verbose lifecycle pluralsight-redux-starter@1.0.0~start: CWD: C:\Users\Tumise\dev\prs
15 silly lifecycle pluralsight-redux-starter@1.0.0~start: Args: [ '/d /s /c',
15 silly lifecycle   'npm-run-all --parallel test:watch open:src lint:watch' ]
16 silly lifecycle pluralsight-redux-starter@1.0.0~start: Returned: code: 1  signal: null
17 info lifecycle pluralsight-redux-starter@1.0.0~start: Failed to exec start script
18 verbose stack Error: pluralsight-redux-starter@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\Tumise\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\Tumise\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid pluralsight-redux-starter@1.0.0
20 verbose cwd C:\Users\Tumise\dev\prs
21 verbose Windows_NT 10.0.17134
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tumise\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 verbose node v10.15.2
24 verbose npm  v6.9.0
25 error code ELIFECYCLE
26 error errno 1
27 error pluralsight-redux-starter@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
27 error Exit status 1
28 error Failed at the pluralsight-redux-starter@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by coryhouse** [comment]
This repo is outdated. Why are you posting here? How did you find this repo?

You're running code from a previous version of the course. Where are you viewing the course?

**Comment by Blac-Panda** [comment]
Puralsight

**Comment by Blac-Panda** [comment]
Oh, just logged into my pluralsight account and the updated version is there, but I can't find it on the offline player

**Comment by coryhouse** [comment]
I can see it in the offline player on Mac: https://www.dropbox.com/s/vrmy4gm1x1azw39/Screenshot%202019-04-03%2008.04.55.png?dl=0

What offline player are you using?

**Comment by Blac-Panda** [comment]
pluralsight offline player for windows

**Comment by Blac-Panda** [comment]
![ps error](https://user-images.githubusercontent.com/23406970/55481667-cbcf2700-561a-11e9-9a63-91fd6b16b5a1.JPG)

**Comment by Blac-Panda** [comment]
I'm guessing the issue is probably with my pluralsight account

**Comment by coryhouse** [comment]
What do you see when you load the course on Pluralsight.com? Can you show me a screenshot of that?

**Comment by coryhouse** [comment]
Oops ignore my previous comment - I see you already answered that. Is there a way to update the list on windows? On Mac there is...

**Comment by coryhouse** [comment]
Ah! I just downloaded the Windows offline player. The updated course is being displayed just fine, but the date displayed is the "created" date instead of the "update" date. So you should be able to watch the new version offline just fine. 

That said, I've emailed Pluralsight to fix this date issue. Thanks for pointing this out! 👍

**Comment by Blac-Panda** [comment]
oh alright
