### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by jlu344** [coryhouse/pluralsight-redux-starter#22]
Node version: 6.4.0, 5.12.0

npm version: 3.10.3

Operating system: 10.0.10586

Command line used: npm start

Steps to reproduce: Steps in Starter Kit

Hi Cory, 

Tried to download and run demo, however, getting the following error.  I tried  the solutions in previous issues, however, no luck.  Enclosed is the log.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pluralsight-redux-starter@1.0.0~prestart: pluralsight-redux-starter@1.0.0
6 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\john\Redux-Startup\pluralsight-redux-starter-master\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\john\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\john\AppData\Local\atom\bin;C:\Users\john\AppData\Roaming\npm
8 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: CWD: C:\Users\john\Redux-Startup\pluralsight-redux-starter-master
9 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Args: [ '/d /s /c', 'babel-node tools/startMessage.js' ]
10 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle pluralsight-redux-starter@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: pluralsight-redux-starter@1.0.0 prestart: `babel-node tools/startMessage.js`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:852:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid pluralsight-redux-starter@1.0.0
14 verbose cwd C:\Users\john\Redux-Startup\pluralsight-redux-starter-master
15 error Windows_NT 10.0.10586
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 error node v6.4.0
18 error npm  v3.10.3
19 error code ELIFECYCLE
20 error pluralsight-redux-starter@1.0.0 prestart: `babel-node tools/startMessage.js`
20 error Exit status 1
21 error Failed at the pluralsight-redux-starter@1.0.0 prestart script 'babel-node tools/startMessage.js'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the pluralsight-redux-starter package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     babel-node tools/startMessage.js
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs pluralsight-redux-starter
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls pluralsight-redux-starter
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

Thanks..

**Comment by jlu344** [comment]
Found the issue.  I'm using Atom text editor and the terminal package I used was causing installation issues with npm install.  I ran npm install from a command prompt and the install ran fine.  However, started getting an es6.symbol error.  So I downgraded to node v5.12.0 and removed and reinstalled using npm install and its running now.  Thanks..
