### ISSUE TITLE
Error on routes.js file

### ISSUE THREAD

**Issue by claudneto** [coryhouse/pluralsight-redux-starter#50]
Node version: 7.7.2

npm version: 4.1.2

Operating system: Ubuntu 16.04

Command line used: npm start -s

Steps to reproduce: Follow the course until "Create Header" chapter

I followed the pluralsight course and I got some errors in IDE (I'm using Visual Studio Code). I thougt it happened because I didn't set up some extensions to work with React and ES6, but when I ran the application (after create routes.js file), I got some errors and I couldn't run it.

ES Lint errors
```
/home/***/src/components/about/AboutPage.js (1/0)
  ✖  6:13  Parsing error: Unexpected token <

/home/***/src/components/App.js (1/0)
  ✖  6:13  Parsing error: Unexpected token <

/home/***/src/components/home/HomePage.js (1/0)
  ✖  7:13  Parsing error: Unexpected token <

/home/***/src/index.js (2/2)
  ✖  5:20  Parse errors in imported module './routes': Unexpected token < (8:5)  import/namespace
  ✖  5:20  Parse errors in imported module './routes': Unexpected token < (8:5)  import/default
  !  5:20  Parse errors in imported module './routes': Unexpected token < (8:5)  import/no-named-as-default
  !  5:20  Parse errors in imported module './routes': Unexpected token < (8:5)  import/no-named-as-default-member

/home/***/src/routes.js (1/0)
  ✖  8:5  Parsing error: Unexpected token <

/home/***/tools/srcServer.js (0/1)
  !  24:5  Unexpected console statement  no-console
```
Babel error
```
ERROR in ./src/routes.js
Module build failed: SyntaxError: /home/***/src/routes.js: Unexpected token (8:4)
   6 |
   7 | export default {
>  8 |     <Route path="/" component={App}>
     |     ^
   9 |         <IndexRoute component={HomePage} />
  10 |         <Rout path="about" component={AboutPage} />
  11 |     </Route>
    at Parser.pp$5.raise (/home/***/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/home/***/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$3.parseIdentifier (/home/***/node_modules/babylon/lib/index.js:4251:10)
    at Parser.pp$3.parsePropertyName (/home/***/node_modules/babylon/lib/index.js:4075:96)
    at Parser.parsePropertyName (/home/***/node_modules/babylon/lib/index.js:5999:23)
    at Parser.pp$3.parseObj (/home/***/node_modules/babylon/lib/index.js:3965:12)
    at Parser.pp$3.parseExprAtom (/home/***/node_modules/babylon/lib/index.js:3652:19)
    at Parser.parseExprAtom (/home/***/node_modules/babylon/lib/index.js:7016:22)
    at Parser.pp$3.parseExprSubscripts (/home/***/node_modules/babylon/lib/index.js:3427:19)
    at Parser.pp$3.parseMaybeUnary (/home/***/node_modules/babylon/lib/index.js:3407:19)
 @ ./src/index.js 13:14-33
ERROR: lint:watch: None-Zero Exit(1);
```
Routes.js
```
import React from 'react';
import { Route, IndexRoute } from 'react-router';
import App from './components/App';
import HomePage from './components/home/HomePage';
import AboutPage from './components/home/AboutPage';

export default {
    <Route path="/" component={App}>
        <IndexRoute component={HomePage} />
        <Rout path="about" component={AboutPage} />
    </Route>
};
```

**Comment by coryhouse** [comment]
It looks like you don't have a .babelrc in the root of your project. Please confirm.

If that doesn't work, please upload your work to GitHub and I'll give it a look.

**Comment by claudneto** [comment]
I have .babelrc in the root.

I created a new repo to upload all my files: https://github.com/claudneto/Pluralsight.ReactRedux
Sorry about forgeting to ignore node_modules folder.

**Comment by coryhouse** [comment]
Your routes.js file is incorrect. Please compare to the course exercise files on the course site.
