### ISSUE TITLE
Running the app for the first time failed at start script

### ISSUE THREAD

**Issue by sridharrreddy** [coryhouse/pluralsight-redux-starter#64]
Node version: 
5.12.0 | 6.11.0 | 7.10.0 | 8.1.2

npm version: 
5.0.3

Operating system: 
Windows 10

Command line used: 
Command Prompt: npm start

Steps to reproduce:
Had same issue with all the node versions mentioned above
_pluralsight-redux-starter_ project works fine though.

Followed the exact steps till Environment Setup > Create Start Script
Excerpt from package.json
`"scripts": {
    "start": "babel-node tools/srcServer.js"
  }`
Replacing `"scripts"` in _pluralsight-redux-starter_ project with above block still works.

**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pluralsight-redux-starter@1.0.0~prestart: pluralsight-redux-starter@1.0.0
6 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle pluralsight-redux-starter@1.0.0~start: pluralsight-redux-starter@1.0.0
8 verbose lifecycle pluralsight-redux-starter@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle pluralsight-redux-starter@1.0.0~start: PATH: C:\Users\sridh\AppData\Roaming\nvm\v6.11.0\node_modules\npm\bin\node-gyp-bin;F:\Projects\ReduxApp\node_modules\.bin;...C:\Program Files\nodejs
10 verbose lifecycle pluralsight-redux-starter@1.0.0~start: CWD: F:\Projects\ReduxApp
11 silly lifecycle pluralsight-redux-starter@1.0.0~start: Args: [ '/d /s /c', 'babel-node tools/srcServer.js' ]
12 silly lifecycle pluralsight-redux-starter@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle pluralsight-redux-starter@1.0.0~start: Failed to exec start script
14 verbose stack Error: pluralsight-redux-starter@1.0.0 start: `babel-node tools/srcServer.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\sridh\AppData\Roaming\nvm\v6.11.0\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\sridh\AppData\Roaming\nvm\v6.11.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid pluralsight-redux-starter@1.0.0
16 verbose cwd F:\Projects\ReduxApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error pluralsight-redux-starter@1.0.0 start: `babel-node tools/srcServer.js`
22 error Exit status 1
23 error Failed at the pluralsight-redux-starter@1.0.0 start script 'babel-node tools/srcServer.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pluralsight-redux-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/srcServer.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pluralsight-redux-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pluralsight-redux-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by coryhouse** [comment]
Can you please post on the course discussion instead? I'm trying to keep all conversations there so others can benefit. Also, please check the list of things to check in this repository read me.

**Comment by Blac-Panda** [comment]
Hi, I'm having this same issues. Can you please direct me to the course discussion where this was solved?
