### ISSUE TITLE
Environment setup: Error when running: npm start

### ISSUE THREAD

**Issue by giovanniroos** [coryhouse/pluralsight-redux-starter#72]
Node version:  v6.9.1

npm version: v3.10.8

Operating system: windows 7

Command line used: npm start

Steps to reproduce:

I am getting an error when I run 'npm start'

From package.json:

..."scripts": {
"prestart": "babel-node tools/startMessage.js",
"start": "npm-run-all --parallel open:src lint:watch",
"open:src": "babel-node tools/srcServer.js",
"lint": "node_modules/.bin/esw webpack.config.* src tools",
"lint:watch": "npm run lint -- --watch"
},...

From my terminal:

D:\liver\source\training\react-redux>npm start

pluralsight-redux-starter@1.0.0 prestart D:\liver\source\training\react-redux
babel-node tools/startMessage.js
Starting app in dev mode...

pluralsight-redux-starter@1.0.0 start D:\liver\source\training\react-redux
npm-run-all --parallel open:src lint:watch
Error: Failed parsing JSON config key editor: "C:\Program Files (x86)\Notepad++\notepad++.exe"
at parseField (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:379:13)
at C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:335:17
at Array.forEach (native)
at Conf.add (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:334:23)
at ConfigChain.addEnv (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:207:15)
at Conf.addEnv (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:359:30)
at load_ (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:107:8)
at Conf. (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:96:5)
at emitOne (events.js:96:13)
at Conf.emit (events.js:188:7)

C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\npm.js:39
throw new Error('npm.load() required')
^

Error: npm.load() required
at Object.get (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\npm.js:39:13)
at exit (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:60:40)
at process.errorHandler (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:180:3)
at emitOne (events.js:96:13)
at process.emit (events.js:188:7)
at processEmit (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
at processEmit [as emit] (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\si
gnal-exit\index.js:146:32)
at process.fatalException (bootstrap_node.js:296:26)
Error: Failed parsing JSON config key editor: "C:\Program Files (x86)\Notepad++\notepad++.exe"
at parseField (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:379:13)
at C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:335:17
at Array.forEach (native)
at Conf.add (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:334:23)
at ConfigChain.addEnv (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:207:15)
at Conf.addEnv (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:359:30)
at load (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:107:8)
at Conf. (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:96:5)
at emitOne (events.js:96:13)
at Conf.emit (events.js:188:7)

C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\npm.js:39
throw new Error('npm.load() required')
^

Error: npm.load() required
at Object.get (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\npm.js:39:13)
at exit (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:60:40)
at process.errorHandler (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:180:3)
at emitOne (events.js:96:13)
at process.emit (events.js:188:7)
at processEmit (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
at processEmit [as emit] (C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\si
gnal-exit\index.js:146:32)
at process._fatalException (bootstrap_node.js:296:26)
ERROR: open:src: None-Zero Exit(7);

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\giovanni1\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! pluralsight-redux-starter@1.0.0 start: npm-run-all --parallel open:src lint:watch
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 start script 'npm-run-all --parallel open:src lint:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pluralsight-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm-run-all --parallel open:src lint:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs pluralsight-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls pluralsight-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! D:\liver\source\training\react-redux\npm-debug.log

NOTE: If I run: 'npm run lint -- --watch' all works perfect..

**Comment by coryhouse** [comment]
Sounds like a syntax error in package.json. If that doesn't help, upload your project to Github I'll give it a glance.

**Comment by coryhouse** [comment]
Closing since no reply. Please reopen if issue persists.
