### ISSUE TITLE
Environment set up : 

### ISSUE THREAD

**Issue by vidhimishra** [coryhouse/pluralsight-redux-starter#73]
Node version: v6.10.3
npm Version : 3.10.10
windows : 10

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\tools\srcServer.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at C:\Vidhi\react-2\hello-world\node_modules\babel-cli\lib\_babel-node.js:171:48

C:\Vidhi\react-2\hello-world>npm -v
3.10.10

C:\Vidhi\react-2\hello-world>node -version
node: bad option: -version

C:\Vidhi\react-2\hello-world>node -ver
node: bad option: -ver

C:\Vidhi\react-2\hello-world>node -v
v6.10.3

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\tools\srcServer.js:3
import webpack from 'webpack';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at C:\Vidhi\react-2\hello-world\node_modules\babel-cli\lib\_babel-node.js:171:48

C:\Vidhi\react-2\hello-world>npm install webpack
pluralsight-redux-starter@1.0.0 C:\Vidhi\react-2\hello-world
`-- webpack@1.13.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint@^3.19.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-import@^2.2.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-react@^7.0.1 but none was installed.
npm WARN eslint-plugin-jsx-a11y@5.0.3 requires a peer of eslint@^2.10.2 || 3.x but none was installed.
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\tools\srcServer.js:5
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at C:\Vidhi\react-2\hello-world\node_modules\babel-cli\lib\_babel-node.js:171:48

C:\Vidhi\react-2\hello-world>npm install path
pluralsight-redux-starter@1.0.0 C:\Vidhi\react-2\hello-world
`-- path@0.12.7
  `-- process@0.11.10

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint@^3.19.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-import@^2.2.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-react@^7.0.1 but none was installed.
npm WARN eslint-plugin-jsx-a11y@5.0.3 requires a peer of eslint@^2.10.2 || 3.x but none was installed.
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.

C:\Vidhi\react-2\hello-world>npm install open
pluralsight-redux-starter@1.0.0 C:\Vidhi\react-2\hello-world
`-- open@0.0.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint@^3.19.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-import@^2.2.0 but none was installed.
npm WARN eslint-config-react-app@1.0.5 requires a peer of eslint-plugin-react@^7.0.1 but none was installed.
npm WARN eslint-plugin-jsx-a11y@5.0.3 requires a peer of eslint@^2.10.2 || 3.x but none was installed.
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\webpack.config.dev.js:1
(function (exports, require, module, __filename, __dirname) { import webpack from 'webpack';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\webpack.config.dev.js:4
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

C:\Vidhi\react-2\hello-world>npm start -s
C:\Vidhi\react-2\hello-world\webpack.config.dev.js:8
export default {
^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Vidhi\react-2\hello-world\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

[src.zip](https://github.com/coryhouse/pluralsight-redux-starter/files/1217360/src.zip)

**Comment by coryhouse** [comment]
Check this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

Let me know if that doesn't fix it. You likely don't have a .babelrc in the root of your project.

**Comment by coryhouse** [comment]
Is this issue resolved?

**Comment by indurnath** [comment]
I am also facing the same issue, Unexpected token Import on srcServer.js while running npm start. Any solutions for this ? I couldn't find any help from : https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first as well .

**Comment by coryhouse** [comment]
Does the final course exercise published on the course page listed under "Exercise files" work for you? Check the final module's folder for the final solution.

**Comment by coryhouse** [comment]
@vidhimishra - This should have been resolved with the changes in #78. Please reopen if this issue persists.
