### ISSUE TITLE
npm start error: Failed at the pluralsight-redux-starter@1.0.0 open:src script 'babel-node tools/srcServer.js'

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [coryhouse/pluralsight-redux-starter#9]
Node version:
6.2.2
npm version:
3.9.5
Operating system:
Mac 10.11.5
Command line used:
npm start
Steps to reproduce:
1) clone
2) npm install
3) npm start
4) get error and see that i need to upgrade node from 5.x to 6.x so do that
5) try again, get error and see issue suggesting deleting node_modules and rerunning ```npm install```
6) tried deleting and rerunning ```npm install``
7) getting error below

```
Ryans-MacBook-Air:pluralsight-redux-starter ryanvice$ npm start

> pluralsight-redux-starter@1.0.0 prestart /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> babel-node tools/startMessage.js

Starting app in dev mode...

> pluralsight-redux-starter@1.0.0 start /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> npm-run-all --parallel test:watch open:src lint:watch


> pluralsight-redux-starter@1.0.0 test:watch /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> npm run test -- --watch


> pluralsight-redux-starter@1.0.0 open:src /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> babel-node tools/srcServer.js


> pluralsight-redux-starter@1.0.0 lint:watch /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> npm run lint -- --watch


> pluralsight-redux-starter@1.0.0 test /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> mocha --reporter progress tools/testSetup.js "src/**/*.test.js" "--watch"


> pluralsight-redux-starter@1.0.0 lint /Users/ryanvice/Documents/Code/pluralsight-redux-starter
> esw webpack.config.* src tools "--watch"


events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/Users/ryanvice/Documents/Code/pluralsight-redux-starter/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (srcServer.js:24:5)
    at Module._compile (module.js:541:32)
    at loader (/Users/ryanvice/Documents/Code/pluralsight-redux-starter/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryanvice/Documents/Code/pluralsight-redux-starter/node_modules/babel-register/lib/node.js:168:7)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "open:src"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! pluralsight-redux-starter@1.0.0 open:src: `babel-node tools/srcServer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 open:src script 'babel-node tools/srcServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pluralsight-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/srcServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pluralsight-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pluralsight-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ryanvice/Documents/Code/pluralsight-redux-starter/npm-debug.log
ERROR: open:src: None-Zero Exit(1);

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! pluralsight-redux-starter@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pluralsight-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel test:watch open:src lint:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pluralsight-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pluralsight-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ryanvice/Documents/Code/pluralsight-redux-starter/npm-debug.log
```

**Comment by coryhouse** [comment]
Note this line: listen EADDRINUSE :::3000

That means you already have something running on Port 3000. :)

**Comment by RyanAtViceSoftware** [comment]
@coryhouse oh jees, how embarassing.

in my defense, i really enjoyed your course. i think it's the best resource on react\redux to date, i liked it better than Dan's series. so i was trying all the things you recomended and not being used to using web storm i didn't realize that the terminal was still running. i'm used to seeing the terminals in the mac menu bar thing. anyway, thanks for the quick response and my apologies for how silly this is.

**Comment by coryhouse** [comment]
@RyanAtViceSoftware Wow, thanks for the kinds words! :)

**Comment by Riki-1mg** [comment]
change the port
